version: '3.8'

services:

  web:
    build: .
    container_name: web
    volumes:
      - ./:/app
    env_file: .env

  nginx:
    container_name: "nginx"
    restart: always
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    links:
      - web