version: '3.8'

services:

  web:
    build: .
    container_name: web
    environment:
      PG_DSN: "..."
    ports:
      - "8080:8080"
    volumes:
      - ./:/app

  nginx:
    container_name: "nginx"
    restart: always
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    links:
      - web